### ISSUE TITLE
[Feature Request] Port rack upgrade logic to controllers

### ISSUE THREAD

**Issue by jzisser9** [ldtteam/StorageRacks#12]
It's possible to upgrade a placed rack to the next tier by left-clicking it with the proper upgrade material in hand. This is really convenient, and it'd be nice if you could do the same with controllers, especially considering upgrades (sort/insert) are lost when the controller is broken.

**Comment by Raycoms** [comment]
Exists, it's just the block form not the ingot form.

**Comment by jzisser9** [comment]
Hey @Raycoms , just to make sure I understand. Do you mean you can use, say, a Block of Iron to upgrade a Stone Controller to an Iron Controller by just clicking it with the block in your hand?
