### ISSUE TITLE
[Bug] Controller insert/sort upgrades are lost when broken

### ISSUE THREAD

**Issue by jzisser9** [ldtteam/StorageRacks#13]
When breaking a controller, the insert/sort upgrades are gone, and so are the materials used for it. Ideally the controller should also drop those items if it has those upgrades.

**Comment by jzisser9** [comment]
I'm happy to work on a PR for this if you'd like to assign it to me.

**Comment by Raycoms** [comment]
This is actually intended "it's a feature". There are not a lot of resource sinks. So, there is a little cost for repositioning. The upgrade is done on left click.

**Comment by jzisser9** [comment]
Oh? Okay, if this is intentional, I'll close the issue.

**Comment by Raycoms** [comment]
If you're interested you could drop some "left over resources" of the upgrade to make this more clear (3 redstone dust, a chest and an iron ingot) or so.
