### ISSUE TITLE
[Bug] Controller rack capacity is 1 less than advertised

### ISSUE THREAD

**Issue by jzisser9** [ldtteam/StorageRacks#14]
See screenshot:

![2022-01-07_15 14 44](https://user-images.githubusercontent.com/3951240/148601785-64025e3b-77ae-428b-8e63-d1698ed2ff17.png)

**Comment by Raycoms** [comment]
Oh no, did I do the classic < instead of <= =D

**Comment by jzisser9** [comment]
Wouldn't be the first time I've done it! :)

**Comment by jzisser9** [comment]
Hmm...this is where I thought the issue would be:

```
EventManager.java:62

if (posSet.size() > controller.getTier() * 20)
```

But if we consider a stone controller to be `tier == 1`, then this logic works. So maybe `posSet.size()` is the issue...

**Comment by jzisser9** [comment]
Just did a little more testing in-game, and it's not just the stone controller that has this issue. All controllers support one less rack than they advertise.

I think it's because of that code snippet I shared above. My guess is that `posSet.size()` is including a block it shouldn't be, like maybe the controller itself.
