### ISSUE TITLE
[Bug/Feature Request]  Make racks drop instead of disappear when Invalid Placement

### ISSUE THREAD

**Issue by mcmanustfj** [ldtteam/StorageRacks#16]
Version 1.18-1.0.2

As it is, when you try to place a rack without a controller, it immediately disappears, without dropping the rack.  I don't know if this is intentional or not, but I think it should drop the item so the resources aren't wasted on a misclick.

**Comment by Raycoms** [comment]
it should just stay in your inventory

**Comment by mcmanustfj** [comment]
On my version (1.18-1.0.2) it disappears and doesn't stay in my inventory.

**Comment by mcmanustfj** [comment]
nevermind, the sprite goes invisible but it's still in the inventory.

**Comment by aelfwyne** [comment]
For me it seems to be going away. If I have a stack of say 10 diamond racks, try to place an invalid one, now I have 9 diamond racks.
