### ISSUE TITLE
Add connector block

### ISSUE THREAD

**Issue by ncottrill** [ldtteam/StorageRacks#19]
Please consider adding a block that could be tucked behind a beam or wall, or under a floor, that will allow storage rack units to stay connected to the controller ... without having to put down another rack.

In many decorations there will be columns or other blocks that are in a pattern that we want to preserve. Being able to hide a rack connection with a connector block under a floor or behind a wall would solve this problem.

**Comment by Talyda** [comment]
Yes! Many times yes! Please?  (that is one you did say you would think about =D)

**Comment by aelfwyne** [comment]
There is a connector block. It's the "corner" piece. Unfortunately it does not connect as an inventory, only for the controller. This means other mods won't see it as a connected inventory.

**Comment by Raycoms** [comment]
Done
