### ISSUE TITLE
[1.16.5] Failed to load correctly.

### ISSUE THREAD

**Issue by GottJammern** [ldtteam/StorageRacks#2]
As title, upon loading throws this error.
[crash-2021-05-29_21.40.09-fml.txt](https://github.com/ldtteam/StorageRacks/files/6565560/crash-2021-05-29_21.40.09-fml.txt)

**Comment by ravenbuilder934** [comment]
Github gist of the crash report: https://gist.github.com/ravenbuilder934/1e8d5b3274c22726affcf890b29fa3bb 

ray you shouldn't be using structurize stuff 😛

**Comment by Raycoms** [comment]
Yeah, you need to install Structurize. And I'm using it, and I'll keep using it for the UI =D

**Comment by ravenbuilder934** [comment]
then make it a dependency in the mods.toml!
