### ISSUE TITLE
Crashing on Testing New Pack

### ISSUE THREAD

**Issue by Zelioth** [ldtteam/StorageRacks#21]
Howdy, Testing a new pack that I am creating for my other packs "Friends United" 

Testing adding storage racks and finding random crash events when loading into the world in creative mode and pressing E to enter the inventory instantly crashes the client. 

I'll provide the information as follows: 
Minecraft 1.19.3
Forge 44.0.23
Storage Racks 1.19.3-1.1.2

https://crashy.net/gm4SW97QvnLUdCuuqT1D

This crashy link has both the raw format crash report and the "attempted to pinpoint mod" error

**Comment by Raycoms** [comment]
Forge pushed some changes it seems, I'll push an update out right now
