### ISSUE TITLE
[Feature] Visual enhancement for rack's container like Minecolonies' racks

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/StorageRacks#26]
Hi, I think if the storage racks have the same item displaying feature like minecolonies's racks would be awesome, as players can observe what is in them.

**Comment by Raycoms** [comment]
Already done for the newer versions

**Comment by pantsguyapp** [comment]
Why are non solid blocks being displayed as barrels?

**Comment by Raycoms** [comment]
We can only actually render item blocks on the barrels, normal items we cant display in minecolonies either
