### ISSUE TITLE
Feature resquest: Keeping the mod up to date.

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/StorageRacks#28]
Hi, I've been enjoying using this mod along side Minecolonies for super compact and efficient storage system without abusing power of virtual system, and I got a few suggestion that the mod may find useful to implement, these are mostly about keeping the mod in trend with the newer minecraft 1.20 versions:

- [x] Cherry plank rack variants: For 1.20 versions.
- [x] Netherrite tier for controller, corners and racks: I know netherrite have quirky implementing mechanic unlike traditional materials, but maybe the devs can come up with something to upgrade to netherrite tier.

**Comment by Raycoms** [comment]
Done for 1.20.1

**Comment by pantsguyapp** [comment]
I want netherrite for 1.19 racks too, is that okay? :))
