### ISSUE TITLE
Unlocks are lost on pickup

### ISSUE THREAD

**Issue by xannor** [ldtteam/StorageRacks#3]
I used a red-stone block to unlock the sorting in a stone controller, then promptly broke the controller. When it broke the red-stone block was not returned, and when placed again, the controller needed another red-stone block to unlock sorting again. Not sure if this is a "feature" or bug, but I don't see it noted anywhere so I figured I would report it.

**Comment by Raycoms** [comment]
Yes, this is intended so far. I'm still in the balancing phase of the mod. But so far I've set this as a "reposition-cost".
I might adjust this in the future if I think it creates counter-incentives to what I actually want. But so far I'm happy with it.
