### ISSUE TITLE
Error to start MC

### ISSUE THREAD

**Issue by albertosaurio65** [ldtteam/StorageRacks#30]
[latest.log](https://github.com/ldtteam/StorageRacks/files/12664482/latest.log)
![image](https://github.com/ldtteam/StorageRacks/assets/70109413/2408d215-1161-4f77-bbea-a0dcd1a33b0b)
[crash-2023-09-19_18.47.58-fml.txt](https://github.com/ldtteam/StorageRacks/files/12664490/crash-2023-09-19_18.47.58-fml.txt)

**Comment by Raycoms** [comment]
You need domum ornamentum together

**Comment by Raycoms** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/domum-ornamentum/files
