### ISSUE TITLE
Feature request: Double rack

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/StorageRacks#35]
Racks can now auto-connect to one another like a double chest, **provided if the adjacent rack is of the same type,** **you can shift right click the rack on the other rack and they will connect**, else they will stay separated, like vanilla chests. 
Controller works fine in recognizing them.

Idea from minecolonies.

**Comment by Raycoms** [comment]
I dont do it on purpose because that would result in larger inventories that need scrolling
