### ISSUE TITLE
Feature request: Bamboo style racks for 1.20

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/StorageRacks#37]
Forgot that beside the cherry wood, there is the slightly less known stripped block of bamboo that can be made into every items in a wood set in 1.20.

Maybe the stripped bamboo can be made into racks also?

**Comment by Raycoms** [comment]
I had added the bamboo planks too

**Comment by pantsguyapp** [comment]
Aww thats so cute. :) :) :)
