### ISSUE TITLE
storage racks NEEDS domum and minecolonies

### ISSUE THREAD

**Issue by redgoblin88** [ldtteam/StorageRacks#48]
in 1.21.1 without domum ornamemum and minecolinies, the mod just crashes
i was hoping i could use this storage racks mod as a standalone, without minecolonies as i am only looking fora storage mod with inventory smaller than 27 slots

neoforge: 21.1.80
storage racks: 1.11-1.21.1
domum ornamemum: 1.0.204-1.21.1
minecolonies: 1.1.802-1.21.1
structurize: 1.0.755-1.21.1

crashlog:
[crash-2024-11-21_11.50.58-fml.txt](https://github.com/user-attachments/files/17845306/crash-2024-11-21_11.50.58-fml.txt)

**Comment by Raycoms** [comment]
actually it needs domum and blockui, it does not need minecolonies

**Comment by redgoblin88** [comment]
i get that crash if i do not have minecolonies (i do have blockui)

if i do have minecolonies it does work

**Comment by Raycoms** [comment]
BlockUI is not there (according to the log)

**Comment by redgoblin88** [comment]
thats odd, i had a look and its installed, i didnt add it myself as i usually assume mods install dependencies.

it must have downloaded blockUI when it successfully launched with minecolonies installed, maybe without minecolonies it fails to check if blockUI is there/to download it?

**Comment by Raycoms** [comment]
Yes, it maybe didn't auto download it, let me check if its marked correctly on cf for 1.21

**Comment by Raycoms** [comment]
Made sure it's properly marked on cf now
