### ISSUE TITLE
Crashing when searching.

### ISSUE THREAD

**Issue by BryanGun** [ldtteam/StorageRacks#49]
latest version/neoforge

When searching an item on controller the game crashes.

First input is ok, second one = crash.

**Comment by Raycoms** [comment]
Hi, can I have the crashlog please?

**Comment by BryanGun** [comment]
[crash-2024-12-04_12.23.48-client.txt](https://github.com/user-attachments/files/18010517/crash-2024-12-04_12.23.48-client.txt)

**Comment by Raycoms** [comment]
Uploaded fix. Another mod is doing derp, but I added some tolerance for that now.
