### ISSUE TITLE
Warped (and all other) Wood Racks don't use tags for the central items

### ISSUE THREAD

**Issue by vizthex123** [ldtteam/StorageRacks#6]
It's quite odd how the plank & sticks in the centre of the recipe don't use their respective tags, could this be fixed?

![image](https://user-images.githubusercontent.com/31721920/126230602-912ccb18-e570-4aee-be25-5f53a80092da.png)

**Comment by Raycoms** [comment]
Done

**Comment by vizthex123** [comment]
noice
