### ISSUE TITLE
[1.17.1] Client crash when opening the controller in creative

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/StorageRacks#8]
https://gist.github.com/ProsperCraft/084798ae19bef6d3a70f5a3ae62fcca5
I placed a controller and a rack in creative, then opened the controller.

**Comment by ProsperCraft** [comment]
RE-loading the world and going in to survival and opening it also crashes the client.

**Comment by Raycoms** [comment]
Working on it.

**Comment by ProsperCraft** [comment]
When you can :)

It seems to be the best storage option in 1.17.1 right now

**Comment by Raycoms** [comment]
Waiting for curseforge for two weaks to approve the library so that I can push the fix....

**Comment by Raycoms** [comment]
Approved, fix pushed.
