### ISSUE TITLE
[1.17.1] New client crash when opening a controller

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/StorageRacks#9]
https://gist.github.com/ProsperCraft/9f0aff8bd6e399b44003d65fef02bb2a

**Comment by Raycoms** [comment]
You need this dependency: https://www.curseforge.com/minecraft/mc-mods/blockui

**Comment by ProsperCraft** [comment]
Can you crash on startup to require the dep?

**Comment by Raycoms** [comment]
It's supposed to

```
[[dependencies.storagerack]]
    modId="blockui"
    mandatory=true
    versionRange="[0.0.20-ALPHA,)"
    ordering="AFTER"
    side="BOTH"
```
  
If it doesn't there must be something broken with forge.

**Comment by ProsperCraft** [comment]
Resolved by adding blockui
